"""first

Revision ID: 816bfd9211a0
Revises: 
Create Date: 2018-01-09 17:21:03.708509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816bfd9211a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('instructor', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_section_instructor'), 'section', ['instructor'], unique=False)
    op.create_table('roleplay',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('assignments', sa.String(length=4000), nullable=True),
    sa.Column('started', sa.Boolean(), nullable=True),
    sa.Column('section_name', sa.String(length=64), nullable=True),
    sa.Column('group_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_name'], ['section.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roleplay_number'), 'roleplay', ['number'], unique=False)
    op.create_table('attendance_record',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('student_name', sa.String(length=64), nullable=True),
    sa.Column('roleplay', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['roleplay'], ['roleplay.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_record')
    op.drop_index(op.f('ix_roleplay_number'), table_name='roleplay')
    op.drop_table('roleplay')
    op.drop_index(op.f('ix_section_instructor'), table_name='section')
    op.drop_table('section')
    # ### end Alembic commands ###
