"""empty message

Revision ID: 6e73970ce72a
Revises: 
Create Date: 2018-01-11 16:57:31.653056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e73970ce72a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_record',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('student_name', sa.String(length=64), nullable=True),
    sa.Column('roleplay', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['roleplay'], ['roleplay.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_record')
    # ### end Alembic commands ###
