"""empty message

Revision ID: 9871ce2d4862
Revises: 
Create Date: 2018-01-11 18:32:41.646794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9871ce2d4862'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_record',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('student_name', sa.String(length=64), nullable=True),
    sa.Column('roleplay_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['roleplay_id'], ['roleplay.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_record')
    # ### end Alembic commands ###
